---
- name: prerequisites are installed
  ansible.builtin.package:
    name:
      - cabextract
      - xorg-x11-font-utils
      - fontconfig
    state: present

- name: install noto color emoji font
  ansible.builtin.package:
    name: google-noto-color-emoji-fonts
    state: present
  notify: rebuild font cache

#- name: microsoft fonts are installed
#  ansible.builtin.dnf:
#    name: "{{ role_path }}/files/msttcore-fonts-installer-2.6-1.noarch.rpm"
#    state: present
#  notify: rebuild font cache

- name: download and extract nerd fonts
  ansible.builtin.include_tasks: download_extract_fonts.yml
  loop: "{{ fonts }}"
  loop_control:
    loop_var: font

- name: install google fonts
  ansible.builtin.include_tasks: google_fonts.yml

- name: install adobe fonts
  ansible.builtin.include_tasks: adobe_fonts.yml
