---
- name: flatpak is installed
  ansible.builtin.package:
    name: flatpak
    state: present

- name: flathub repository is added
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

