---
- name: flatpak is installed
  ansible.builtin.package:
    name: flatpak
    state: present

- name: flathub repository is added
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: flatpak system overrides directory exists
  ansible.builtin.file:
    path: /var/lib/flatpak/overrides
    state: directory
    mode: 0755

