// Suspend after 30 minutes of inactivity.
spawn-at-startup "swayidle" "-w" "timeout" "1800" "systemctl suspend"

spawn-at-startup "swaybg" "-i" "/home/sean/.local/share/backgrounds/astronaut_jellyfish.jpg" "-m" "fill"
