- name: Configure desktop22 as a workstation
  hosts: localhost
  connection: local
  become: true

  vars:
    user: sean
    uid: 1000
    gid: 1000

  tasks:
    - name: dunst dnd override.conf is absent
      ansible.builtin.file:
        path: /home/{{ user }}/.config/systemd/user/dunst.service.d/override.conf
        state: absent

    - name: dunst systemd drop-in directory is absent
      ansible.builtin.file:
        path: /home/{{ user }}/.config/systemd/user/dunst.service.d
        state: absent

  roles:
    - role: core
    - role: docker
    - role: ansible_pull
    - role: btrfs
    - role: rpm_fusion
    - role: cli
    - role: fonts
    - role: onepassword
    - role: tailscale
    - role: network_storage
    - role: libvirt
    - role: devops
    - role: nodejs
    - role: hyprland
    - role: niri
    - role: gui
    - role: gaming

