- name: Configure odroidh3plus as a server
  hosts: localhost
  connection: local
  become: true

  vars:
    user: sean
    uid: 1000
    gid: 1000
    dnf_automatic_reboot: "when-needed"
    btrbk_volumes:
      - volume: /
        snapshot_dir: /.btrbk_snapshots
        snapshot_preserve: 24h 7d 4w
        subvolumes:
          - home
      - volume: /srv
        snapshot_dir: /srv/.btrbk_snapshots
        snapshot_preserve: 24h 7d 4w 6m
        subvolumes:
          - .

  roles:
    - role: core
    - role: ansible_pull
    - role: dnf
    - role: btrfs
    - role: cli
    - role: karakeep
    - role: retrogaming
      vars:
        user: retrogaming
        emulation_roms_path: /srv/tier2/emulation/roms
        emulation_bios_path: /srv/tier2/emulation/bios
        emulation_saves_path: /srv/tier2/emulation/saves
        emulation_media_path: /srv/tier2/emulation/media
    - role: autologin
      vars:
        user: retrogaming
    - role: libvirt
    - role: fonts
    - role: onepassword
    - role: tailscale
      vars:
        tailscale_advertise_exit_node: true
        tailscale_accept_routes: false
        tailscale_subnet_routes:
          - 192.168.0.0/24
    - role: nextdns
    - role: smb
    - role: nfs
