---
user: sean
network_share_group: networkshare
network_share_gid: 5567
nfs_mounts:
  - server: odroidh3plus
    path: /srv/tier1
  - server: odroidh3plus
    path: /srv/tier2
  - server: odroidh3plus
    path: /source
samba_mounts:
  - server: odroidh3plus
    share: tier1
  - server: odroidh3plus
    share: tier2
bind_mounts:
  - src: /srv/tier1/docs
    path: /home/{{ user }}/u
