---
- name: configure google-chrome repository
  block:
    - name: google repository key is installed
      ansible.builtin.rpm_key:
        key: https://dl.google.com/linux/linux_signing_key.pub
        fingerprint: eb4c1bfd4f042f6dddccec917721f63bd38b4796
        state: present

    - name: google-chrome repository is enabled
      ansible.builtin.yum_repository:
        name: google-chrome
        description: Google Chrome
        baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub
        skip_if_unavailable: true

- name: google chrome is installed
  ansible.builtin.package:
    name: google-chrome-stable

- name: yt-dlp and mpv are installed
  ansible.builtin.package:
    name:
      - yt-dlp
      - mpv
    state: present

- name: vid-play.sh is installed
  ansible.builtin.copy:
    src: vid-play.sh
    dest: /home/{{ user }}/bin/vid-play.sh
    mode: 0755
    owner: "{{ user }}"
    group: "{{ user }}"

- name: /home/{{ user }}/.local/share/applications directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.local/share/applications
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ user }}"

- name: vid-play.desktop is installed
  ansible.builtin.template:
    src: vid-play.desktop.j2
    dest: /home/{{ user }}/.local/share/applications/vid-play.desktop
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"

- name: current vid-play protocol handler
  ansible.builtin.command:
    cmd: xdg-mime query default x-scheme-handler/vid-play
  become: true
  become_user: "{{ user }}"
  register: vidplay_handler
  changed_when: false
  failed_when: false

- name: vid-play protocol handler is registered
  ansible.builtin.command:
    cmd: xdg-mime default vid-play.desktop x-scheme-handler/vid-play
  become: true
  become_user: "{{ user }}"
  when: vidplay_handler.stdout != 'vid-play.desktop'
  changed_when: true

