---
- name: configure google-chrome repository
  block:
    - name: google repository key file is installed
      ansible.builtin.copy:
        src: google_linux_signing_key.pub
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-google
        owner: root
        group: root
        mode: 0644

    - name: google repository key is installed
      ansible.builtin.rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-google
        fingerprint: eb4c1bfd4f042f6dddccec917721f63bd38b4796
        state: present

    - name: google-chrome repository is enabled
      ansible.builtin.yum_repository:
        name: google-chrome
        description: Google Chrome
        baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-google
        skip_if_unavailable: true

- name: google chrome is installed
  ansible.builtin.package:
    name: google-chrome-stable
