---
- name: wayscriber repository is configured
  block:
    - name: wayscriber repository key file is installed
      ansible.builtin.copy:
        src: wayscriber.asc
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-wayscriber
        owner: root
        group: root
        mode: 0644

    - name: wayscriber repository key is installed
      ansible.builtin.rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-wayscriber
        fingerprint: 4489BCBB3CB130533709175F027B1C752E38957A
        state: present

    - name: wayscriber repository is enabled
      ansible.builtin.yum_repository:
        name: wayscriber
        description: Wayscriber Repo
        baseurl: https://wayscriber.com/rpm
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-wayscriber
        skip_if_unavailable: true

- name: wayscriber is installed
  ansible.builtin.package:
    name: wayscriber
    state: present
  notify: enable wayscriber service

- name: wayscriber configurator is installed
  ansible.builtin.package:
    name: wayscriber-configurator
    state: present
