[Unit]
After=dns-online.service
After=ansible-pull.service
After=dnf-makecache.service
Wants=dns-online.service
Wants=dnf-makecache.service

[Service]
EnvironmentFile=-/run/dnf5-automatic.env
ExecStartPre=-/bin/bash -c "echo PRE_NUM=$(snapper create --type pre --print-number --description 'Before dnf5-automatic' --cleanup-algorithm number) > /run/dnf5-automatic.env"
ExecStartPost=-/bin/bash -c "snapper create --type post --pre-number $PRE_NUM --description 'After dnf5-automatic' --cleanup-algorithm number && rm -f /run/dnf5-automatic.env"
