---
- name: ansible-core and ansible-lint are up to date
  ansible.builtin.pip:
    name:
      - ansible-core~={{ ansible_pip_version }}
      - ansible-lint~={{ ansible_lint_pip_version }}
    state: latest  # noqa: package-latest

- name: "{{ playbook_path }} is a safe git directory for root"
  community.general.git_config:
    name: safe.directory
    value: "{{ playbook_path }}"
    scope: global

- name: wheel group can edit {{ playbook_path }}
  ansible.builtin.shell:
    cmd: >-
      find {{ playbook_path }} -xdev
      -not -path '{{ playbook_path }}/docs'
      -not -path '{{ playbook_path }}/.git'
      -not -path '{{ playbook_path }}/.git/*'
      -exec chown root:wheel {} + &&
      find {{ playbook_path }} -xdev
      -not -path '{{ playbook_path }}/docs'
      -not -path '{{ playbook_path }}/.git'
      -not -path '{{ playbook_path }}/.git/*'
      -exec chmod u=rwX,g=rwX,o=rX {} +
  changed_when: false

- name: template ansible-pull systemd service
  ansible.builtin.template:
    src: ansible-pull.service.j2
    dest: /etc/systemd/system/ansible-pull.service
    mode: 0644
    owner: root
    group: root

- name: template ansible-pull systemd timer
  ansible.builtin.template:
    src: ansible-pull.timer.j2
    dest: /etc/systemd/system/ansible-pull.timer
    mode: 0644
    owner: root
    group: root
  notify: restart ansible-pull timer

- name: ansible-pull log directory exists
  ansible.builtin.file:
    path: /var/log/ansible-pull
    state: directory
    mode: 0770
    owner: root
    group: wheel

- name: logrotate is installed
  ansible.builtin.package:
    name: logrotate
    state: present

- name: configure log rotation for ansible-pull
  ansible.builtin.copy:
    content: |
      /var/log/ansible-pull/*.log {
          rotate 30
          maxage 30
          missingok
          notifempty
          nocompress
          nocreate
      }
    dest: /etc/logrotate.d/ansible-pull
    mode: 0640
    owner: root
    group: wheel

- name: enable and start ansible-pull timer
  ansible.builtin.systemd_service:
    name: ansible-pull.timer
    enabled: true
    state: started
    daemon_reload: true

- name: ansible-pull-notify script is deployed
  ansible.builtin.template:
    src: ansible-pull-notify.sh.j2
    dest: /usr/local/bin/ansible-pull-notify.sh
    owner: root
    group: root
    mode: 0755

- name: template homelab management script (h)
  ansible.builtin.template:
    src: h.sh.j2
    dest: /usr/local/bin/h
    mode: 0750
    owner: root
    group: wheel

- name: template homelab management script (h) bash completion
  ansible.builtin.template:
    src: h_completion.bash.j2
    dest: /etc/bash_completion.d/h_completion.bash
    mode: 0640
    owner: root
    group: wheel

