---
- name: plocate is installed
  ansible.builtin.package:
    name: plocate
    state: present

- name: systemd daemon is reloaded
  ansible.builtin.systemd:
    daemon_reload: true
  changed_when: false

- name: PRUNENAMES excludes all snapshot directories
  ansible.builtin.lineinfile:
    path: /etc/updatedb.conf
    regexp: '^PRUNENAMES ='
    line: 'PRUNENAMES = ".snapshots .btrbk_snapshots node-modules"'
    create: true
    state: present
    mode: 0644

- name: plocate-updatedb.timer is enabled and started
  ansible.builtin.service:
    name: plocate-updatedb.timer
    enabled: true
    state: started
