---
- name: plocate is installed
  ansible.builtin.package:
    name: plocate
    state: present

- name: updatedb wrapper is installed
  ansible.builtin.template:
    src: updatedb.j2
    dest: /usr/local/bin/updatedb
    owner: root
    group: root
    mode: 0755

- name: plocate updatedb service override directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/plocate-updatedb.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: plocate updatedb exclusions are configured
  ansible.builtin.template:
    src: plocate-updatedb-override.conf.j2
    dest: /etc/systemd/system/plocate-updatedb.service.d/override.conf
    owner: root
    group: root
    mode: 0644

- name: systemd daemon is reloaded
  ansible.builtin.systemd:
    daemon_reload: true
  changed_when: false

- name: plocate-updatedb.timer is enabled and started
  ansible.builtin.service:
    name: plocate-updatedb.timer
    enabled: true
    state: started
