---
- name: neovim and its dependencies are installed
  ansible.builtin.package:
    name:
      - neovim
      - wl-clipboard
    state: present

- name: neovim image support packages are installed
  ansible.builtin.package:
    name:
      - fd-find
      - ImageMagick
    state: present

- name: vim is aliased to nvim for all users
  ansible.builtin.copy:
    content: "alias vim='nvim'\n"
    dest: /etc/profile.d/nvim-alias.sh
    mode: 0644

- name: symlink nvim dotfiles directory
  ansible.builtin.file:
    src: "{{ dotfiles_path }}/nvim"
    dest: /home/{{ user }}/.config/nvim
    state: link
    follow: false
    owner: "{{ user }}"
    group: "{{ user }}"

