;;; init-test.el --- Tests for init.el -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'org)

(ert-deftest my/evil-normal-state-and-save-enters-normal-state-before-saving ()
  (let (calls)
    (cl-letf (((symbol-function 'evil-normal-state)
               (lambda () (push 'normal-state calls)))
              ((symbol-function 'save-buffer)
               (lambda () (push 'save calls))))
      (my/evil-normal-state-and-save))
    (should (equal (nreverse calls) '(normal-state save)))))

(ert-deftest my/evil-command-and-recenter-runs-in-order ()
  (let (calls)
    (cl-letf (((symbol-function 'call-interactively)
               (lambda (command &optional _record-flag _keys)
                 (push command calls)))
              ((symbol-function 'recenter)
               (lambda (&optional _redisplay)
                 (push 'recenter calls))))
      (my/evil-command-and-recenter #'evil-scroll-down))
    (should (equal (nreverse calls) '(evil-scroll-down recenter)))))

(ert-deftest my/evil-centered-motion-wrappers-dispatch-to-evil-commands ()
  (dolist (entry '((my/evil-scroll-down-and-center . evil-scroll-down)
                   (my/evil-scroll-up-and-center . evil-scroll-up)
                   (my/evil-search-next-and-center . evil-search-next)
                   (my/evil-search-previous-and-center . evil-search-previous)
                   (my/evil-backward-paragraph-and-center
                    . evil-backward-paragraph)
                   (my/evil-forward-paragraph-and-center
                    . evil-forward-paragraph)))
    (let (command)
      (cl-letf (((symbol-function 'my/evil-command-and-recenter)
                 (lambda (value)
                   (setq command value))))
        (funcall (car entry)))
      (should (eq command (cdr entry))))))

(ert-deftest my/copy-file-name-copies-the-basename ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/project/archive.tar.gz")
    (let (copied)
      (cl-letf (((symbol-function 'kill-new)
                 (lambda (text &optional _replace)
                   (setq copied text))))
        (my/copy-file-name))
      (should (equal copied "archive.tar.gz")))))

(ert-deftest my/copy-file-name-rejects-a-non-file-buffer ()
  (with-temp-buffer
    (should-error (my/copy-file-name) :type 'user-error)))

(ert-deftest my/copy-project-relative-file-path-copies-a-relative-path ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/project/src/main.el")
    (let (copied)
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _) 'project))
                ((symbol-function 'project-root)
                 (lambda (_project) "/tmp/project/"))
                ((symbol-function 'kill-new)
                 (lambda (text &optional _replace)
                   (setq copied text))))
        (my/copy-project-relative-file-path))
      (should (equal copied "src/main.el")))))

(ert-deftest my/copy-project-relative-file-path-copies-an-absolute-path-without-a-project ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/notes/todo.org")
    (let (copied)
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _) nil))
                ((symbol-function 'kill-new)
                 (lambda (text &optional _replace)
                   (setq copied text))))
        (my/copy-project-relative-file-path))
      (should (equal copied "/tmp/notes/todo.org")))))

(ert-deftest my/copy-project-relative-file-path-rejects-a-non-file-buffer ()
  (with-temp-buffer
    (should-error (my/copy-project-relative-file-path) :type 'user-error)))

(ert-deftest my/search-symbol-at-point-starts-with-the-current-symbol ()
  (with-temp-buffer
    (insert "alpha beta")
    (goto-char (point-min))
    (let (initial)
      (cl-letf (((symbol-function 'consult-line)
                 (lambda (value &optional _start)
                   (setq initial value))))
        (my/search-symbol-at-point))
      (should (equal initial "alpha")))))

(ert-deftest my/search-symbol-at-point-allows-no-current-symbol ()
  (with-temp-buffer
    (let ((initial 'not-called))
      (cl-letf (((symbol-function 'consult-line)
                 (lambda (value &optional _start)
                   (setq initial value))))
        (my/search-symbol-at-point))
      (should-not initial))))

(ert-deftest my/search-open-buffers-searches-all-buffers ()
  (let (query)
    (cl-letf (((symbol-function 'consult-line-multi)
               (lambda (value &optional _initial)
                 (setq query value))))
      (my/search-open-buffers))
    (should query)))

(ert-deftest my/search-project-symbol-at-point-starts-with-the-current-symbol ()
  (with-temp-buffer
    (insert "alpha beta")
    (goto-char (point-min))
    (let (directory initial)
      (cl-letf (((symbol-function 'consult-ripgrep)
                 (lambda (dir value)
                   (setq directory dir
                         initial value))))
        (my/search-project-symbol-at-point))
      (should-not directory)
      (should (equal initial "alpha")))))

(ert-deftest my/org-find-file-in-notes-searches-org-directory ()
  (let ((org-directory "/tmp/notes")
        arguments)
    (cl-letf (((symbol-function 'project-find-file-in)
               (lambda (&rest values)
                 (setq arguments values))))
      (my/org-find-file-in-notes))
    (should (equal (nth 0 arguments) nil))
    (should (equal (nth 1 arguments) '("/tmp/notes/")))
    (should (equal (project-root (nth 2 arguments)) "/tmp/notes/"))
    (should (equal (nth 3 arguments) t))))

(ert-deftest my/org-browse-notes-opens-org-directory ()
  (let ((org-directory "/tmp/notes")
        directory)
    (cl-letf (((symbol-function 'dired)
               (lambda (value &optional _switches)
                 (setq directory value))))
      (my/org-browse-notes))
    (should (equal directory "/tmp/notes"))))

(ert-deftest my/org-search-notes-searches-org-directory ()
  (let ((org-directory "/tmp/notes")
        directory)
    (cl-letf (((symbol-function 'consult-ripgrep)
               (lambda (&optional value _initial)
                 (setq directory value))))
      (my/org-search-notes))
    (should (equal directory "/tmp/notes"))))

(ert-deftest my/org-command-and-enter-insert-state-runs-in-order ()
  (let (calls)
    (cl-letf (((symbol-function 'call-interactively)
               (lambda (command &optional _record-flag _keys)
                 (push command calls)))
              ((symbol-function 'evil-insert-state)
               (lambda (&optional _count)
                 (push 'insert-state calls))))
      (my/org-command-and-enter-insert-state #'org-insert-subheading))
    (should (equal (nreverse calls)
                   '(org-insert-subheading insert-state)))))

(ert-deftest my/org-meta-return-appends-a-list-item-and-starts-editing ()
  (with-temp-buffer
    (org-mode)
    (insert "- [ ] Existing task")
    (evil-normal-state)
    (search-backward "Existing")
    (my/org-meta-return)
    (should (equal (buffer-string)
                   "- [ ] Existing task\n- "))
    (should (evil-insert-state-p))))

(ert-deftest my/org-meta-shift-return-appends-a-todo-item-and-starts-editing ()
  (with-temp-buffer
    (org-mode)
    (insert "- [ ] Existing task")
    (evil-normal-state)
    (search-backward "Existing")
    (my/org-insert-todo-heading)
    (should (equal (buffer-string)
                   "- [ ] Existing task\n- [ ] "))
    (should (evil-insert-state-p))))

(ert-deftest my/org-open-fold-shows-entry-and-direct-children ()
  (let (calls)
    (cl-letf (((symbol-function 'org-back-to-heading)
               (lambda (&optional invisible-ok)
                 (push `(back-to-heading ,invisible-ok) calls)))
              ((symbol-function 'org-fold-show-entry)
               (lambda (&optional _hide-drawers)
                 (push 'show-entry calls)))
              ((symbol-function 'org-fold-show-children)
               (lambda (&optional _level)
                 (push 'show-children calls))))
      (my/org-open-fold))
    (should (equal (nreverse calls)
                   '((back-to-heading t) show-entry show-children)))))

(ert-deftest my/org-visible-fold-level-detects-the-current-outline-depth ()
  (save-window-excursion
    (with-temp-buffer
      (org-mode)
      (insert "* Parent\n** Child\n*** Grandchild\n")
      (set-window-buffer (selected-window) (current-buffer))
      (goto-char (point-min))
      (outline-hide-sublevels 2)
      (should (= (my--org-visible-fold-level) 2)))))

(ert-deftest my/org-hide-next-fold-level-decreases-the-visible-level ()
  (let (hidden-to)
    (cl-letf (((symbol-function 'my--org-visible-fold-level)
               (lambda () 3))
              ((symbol-function 'outline-hide-sublevels)
               (lambda (level)
                 (setq hidden-to level))))
      (my/org-hide-next-fold-level))
    (should (= hidden-to 2))))

(ert-deftest my/org-hide-next-fold-level-stops-at-level-one ()
  (let (hidden-to)
    (cl-letf (((symbol-function 'my--org-visible-fold-level)
               (lambda () 1))
              ((symbol-function 'outline-hide-sublevels)
               (lambda (level)
                 (setq hidden-to level))))
      (my/org-hide-next-fold-level))
    (should (= hidden-to 1))))

(ert-deftest my/org-show-next-fold-level-increases-the-visible-level ()
  (let (hidden-to)
    (cl-letf (((symbol-function 'my--org-visible-fold-level)
               (lambda () 3))
              ((symbol-function 'outline-hide-sublevels)
               (lambda (level)
                 (setq hidden-to level))))
      (my/org-show-next-fold-level))
    (should (= hidden-to 4))))

(ert-deftest my/org-task-capture-targets-the-inbox-file ()
  (require 'org-capture)
  (let* ((template (assoc "t" org-capture-templates))
         (target (nth 3 template)))
    (should (equal target
                   `(file ,(expand-file-name "inbox.org" org-directory))))))

(ert-deftest my/org-task-capture-separates-top-level-headings ()
  (require 'org-capture)
  (let* ((file (make-temp-file "org-capture-spacing-" nil ".org"
                               "* TODO Existing\n"))
         (template (copy-tree (assoc "t" org-capture-templates)))
         (org-capture-templates (list template)))
    (unwind-protect
        (progn
          (setf (nth 3 template) `(file ,file))
          (org-capture-string "" "t")
          (when (org-capture-get :buffer)
            (org-capture-finalize))
          (with-temp-buffer
            (insert-file-contents file)
            (should (string-match-p
                     "\\* TODO Existing\n\n\\* TODO"
                     (buffer-string)))))
      (ignore-errors (org-capture-kill))
      (delete-file file))))

(ert-deftest my/org-capture-starts-in-evil-insert-state ()
  (require 'org-capture)
  (should (memq #'evil-insert-state org-capture-mode-hook))
  (let ((org-capture-mode-hook '(evil-insert-state))
        called)
    (cl-letf (((symbol-function 'evil-insert-state)
               (lambda (&optional _count)
                 (setq called t))))
      (run-hooks 'org-capture-mode-hook))
    (should called)))

(ert-deftest my/org-rich-text-export-uses-the-active-region ()
  (let (clipboard kill-ring-text)
    (cl-letf (((symbol-function 'kill-new)
               (lambda (text &optional _replace)
                 (setq kill-ring-text text)))
              ((symbol-function 'gui-set-selection)
               (lambda (_type data)
                 (setq clipboard data))))
      (with-temp-buffer
        (org-mode)
        (insert "* First\nSelected *bold* text.\n\n* Second\nExcluded text.\n")
        (goto-char (point-min))
        (set-mark (save-excursion
                    (search-forward "* Second")
                    (line-beginning-position)))
        (activate-mark)
        (my/org-export-to-clipboard-as-rich-text)))
    (let ((html (get-text-property 0 'text/html clipboard)))
      (should (string-match-p "Selected" kill-ring-text))
      (should-not (string-match-p "Excluded" kill-ring-text))
      (should (string-match-p "Selected" html))
      (should (string-match-p "<b>bold</b>" html))
      (should-not (string-match-p "Excluded" html)))))

(ert-deftest my/org-rich-text-export-uses-the-whole-buffer-without-a-region ()
  (let (clipboard kill-ring-text)
    (cl-letf (((symbol-function 'kill-new)
               (lambda (text &optional _replace)
                 (setq kill-ring-text text)))
              ((symbol-function 'gui-set-selection)
               (lambda (_type data)
                 (setq clipboard data))))
      (with-temp-buffer
        (org-mode)
        (insert "* First\nFirst text.\n\n* Second\nSecond text.\n")
        (my/org-export-to-clipboard-as-rich-text)))
    (let ((html (get-text-property 0 'text/html clipboard)))
      (should (string-match-p "First text" kill-ring-text))
      (should (string-match-p "Second text" kill-ring-text))
      (should (string-match-p "First text" html))
      (should (string-match-p "Second text" html)))))

;;; init-test.el ends here
