;;; init-test.el --- Tests for init.el -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'markdown-mode)
(require 'org)

(ert-deftest my/angular-project-root-finds-nearest-angular-workspace ()
  (let* ((root (make-temp-file "angular-project" t))
         (nested (expand-file-name "apps/web/src" root)))
    (unwind-protect
        (progn
          (make-directory nested t)
          (write-region "{}" nil (expand-file-name "angular.json" root))
          (should (equal (my/angular-project-root nested)
                         (file-name-as-directory root))))
      (delete-directory root t))))

(ert-deftest my/angular-project-root-rejects-ordinary-projects ()
  (let ((root (make-temp-file "ordinary-project" t)))
    (unwind-protect
        (should-not (my/angular-project-root root))
      (delete-directory root t))))

(ert-deftest my/project-try-angular-returns-a-transient-project ()
  (cl-letf (((symbol-function 'my/angular-project-root)
             (lambda (&optional _directory) "/tmp/angular/")))
    (should (equal (my/project-try-angular "/tmp/angular/src")
                   '(transient . "/tmp/angular/")))))

(ert-deftest my/kotlin-project-root-finds-nearest-build ()
  (let* ((root (make-temp-file "kotlin-project" t))
         (nested (expand-file-name "src/main/kotlin/example" root)))
    (unwind-protect
        (progn
          (make-directory nested t)
          (write-region "" nil (expand-file-name "settings.gradle.kts" root))
          (should (equal (my/kotlin-project-root nested)
                         (file-name-as-directory root))))
      (delete-directory root t))))

(ert-deftest my/project-try-kotlin-returns-a-transient-project ()
  (cl-letf (((symbol-function 'my/kotlin-project-root)
             (lambda (&optional _directory) "/tmp/kotlin/")))
    (should (equal (my/project-try-kotlin "/tmp/kotlin/src")
                   '(transient . "/tmp/kotlin/")))))

(ert-deftest my/angular-core-version-normalizes-package-version ()
  (let ((root (make-temp-file "angular-version" t)))
    (unwind-protect
        (progn
          (write-region
           "{\"dependencies\":{\"@angular/core\":\"^20.2.1\"}}"
           nil (expand-file-name "package.json" root))
          (should (equal (my/angular-core-version root) "20.2.1")))
      (delete-directory root t))))

(ert-deftest my/angular-language-server-command-includes-probes-and-version ()
  (cl-letf (((symbol-function 'my/angular-node-modules)
             (lambda (_root) '("/tmp/project/node_modules")))
            ((symbol-function 'my/angular-core-version)
             (lambda (_root) "20.2.1")))
    (should
     (equal
      (my/angular-language-server-command "/tmp/project")
      '("ngserver" "--stdio"
        "--tsProbeLocations" "/tmp/project/node_modules"
        "--ngProbeLocations"
        "/tmp/project/node_modules/@angular/language-server/node_modules"
        "--angularCoreVersion" "20.2.1")))))

(ert-deftest my/eglot-typescript-contact-selects-the-angular-multiplexer ()
  (cl-letf (((symbol-function 'my/angular-project-root)
             (lambda (&optional _directory) "/tmp/angular/"))
            ((symbol-function 'my/angular-language-server-command)
             (lambda (_root) '("ngserver" "--stdio"))))
    (should
     (equal (my/eglot-typescript-contact nil '(transient . "/tmp/angular/"))
            '("rass" "--" "typescript-language-server" "--stdio" "--"
              "ngserver" "--stdio")))))

(ert-deftest my/eglot-typescript-contact-selects-the-direct-server ()
  (cl-letf (((symbol-function 'my/angular-project-root)
             (lambda (&optional _directory) nil)))
    (should (equal (my/eglot-typescript-contact nil nil)
                   '("typescript-language-server" "--stdio")))))

(ert-deftest my/eglot-angular-contact-rejects-ordinary-html ()
  (cl-letf (((symbol-function 'my/angular-project-root)
             (lambda (&optional _directory) nil)))
    (should-error (my/eglot-angular-contact nil nil))))

(ert-deftest my/eglot-ensure-angular-html-only-starts-in-angular-projects ()
  (let (started)
    (cl-letf (((symbol-function 'my/angular-project-root)
               (lambda (&optional _directory) "/tmp/angular/"))
              ((symbol-function 'eglot-ensure)
               (lambda () (setq started t))))
      (my/eglot-ensure-angular-html)
      (should started))))

(ert-deftest my/eglot-disable-inlay-hints-disables-an-active-mode ()
  (let ((original (and (boundp 'eglot-inlay-hints-mode)
                       (symbol-value 'eglot-inlay-hints-mode)))
        argument)
    (unwind-protect
        (progn
          (set 'eglot-inlay-hints-mode t)
          (cl-letf (((symbol-function 'eglot-inlay-hints-mode)
                     (lambda (value) (setq argument value))))
            (my/eglot-disable-inlay-hints)
            (should (= argument -1))))
      (set 'eglot-inlay-hints-mode original))))

(ert-deftest my/eglot-clear-connected-message-only-clears-connection-notice ()
  (let (cleared)
    (cl-letf (((symbol-function 'current-message)
               (lambda () "[eglot] Connected! Server ready"))
              ((symbol-function 'message)
               (lambda (&rest _) (setq cleared t))))
      (my/eglot-clear-connected-message)
      (should cleared))
    (setq cleared nil)
    (cl-letf (((symbol-function 'current-message)
               (lambda () "[eglot] (warning) Server problem"))
              ((symbol-function 'message)
               (lambda (&rest _) (setq cleared t))))
      (my/eglot-clear-connected-message)
      (should-not cleared))))

(ert-deftest my/eglot-hierarchy-outgoing-calls-uses-prefix-behavior ()
  (let (argument)
    (cl-letf (((symbol-function 'eglot-hierarchy-call-hierarchy)
               (lambda (&optional value) (setq argument value))))
      (my/eglot-hierarchy-outgoing-calls)
      (should argument))))

(ert-deftest my/eglot-open-roslyn-workspace-opens-csharp-projects ()
  (with-temp-buffer
    (setq major-mode 'csharp-ts-mode)
    (let (notification)
      (cl-letf (((symbol-function 'eglot-managed-p) (lambda () t))
                ((symbol-function 'eglot-current-server)
                 (lambda () 'server))
                ((symbol-function 'project-current) (lambda (&rest _) 'project))
                ((symbol-function 'project-root)
                 (lambda (_project) "/tmp/csharp/"))
                ((symbol-function 'project-files)
                 (lambda (_project) '("Program.cs" "LangTest.csproj")))
                ((symbol-function 'eglot-path-to-uri)
                 (lambda (path) (concat "file://" path)))
                ((symbol-function 'jsonrpc-notify)
                 (lambda (server method params)
                   (setq notification (list server method params)))))
        (my/eglot-open-roslyn-workspace)
        (should
         (equal notification
                '(server :project/open
                  (:projects ["file:///tmp/csharp/LangTest.csproj"]))))))))

(ert-deftest my/ansible-file-p-recognizes-role-and-playbook-files ()
  (should (my/ansible-file-p "/tmp/project/roles/example/tasks/main.yml"))
  (should (my/ansible-file-p "/tmp/project/roles/example/vars/main.yaml"))
  (should (my/ansible-file-p "/tmp/project/site.yml"))
  (should-not (my/ansible-file-p "/tmp/project/.github/workflows/test.yml")))

(ert-deftest my/yaml-ts-mode-selects-ansible-mode ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/project/roles/example/meta/main.yml")
    (cl-letf (((symbol-function 'ansible-ts-mode)
               (lambda () (setq major-mode 'ansible-ts-mode))))
      (my/yaml-ts-mode)
      (should (eq major-mode 'ansible-ts-mode)))))

(ert-deftest my/yaml-ts-mode-preserves-generic-yaml ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/project/.github/workflows/test.yml")
    (cl-letf (((symbol-function 'yaml-ts-mode)
               (lambda () (setq major-mode 'yaml-ts-mode))))
      (my/yaml-ts-mode)
      (should (eq major-mode 'yaml-ts-mode)))))

(ert-deftest my/yaml-mode-dispatcher-precedes-generic-yaml-mode ()
  (let ((entry (seq-find (lambda (candidate)
                           (and (stringp (car-safe candidate))
                                (string-match-p (car candidate)
                                                "/tmp/example.yml")))
                         auto-mode-alist)))
    (should (eq (cdr entry) #'my/yaml-ts-mode))))

(ert-deftest my/eglot-prefers-ansible-server-over-yaml-parent ()
  (require 'eglot)
  (let ((ansible-position (seq-position eglot-server-programs 'ansible-ts-mode
                                        (lambda (entry mode)
                                          (eq mode (car entry)))))
        (yaml-position (seq-position eglot-server-programs 'yaml-ts-mode
                                     (lambda (entry mode)
                                       (eq mode (car entry))))))
    (should ansible-position)
    (should yaml-position)
    (should (< ansible-position yaml-position))))

(ert-deftest my/eglot-enables-ansible-validation-and-lint ()
  (require 'eglot)
  (should
   (equal (plist-get (plist-get eglot-workspace-configuration :ansible)
                     :validation)
          '(:enabled t :lint (:enabled t :path "ansible-lint")))))

(ert-deftest my/kotlin-uses-tree-sitter-mode-and-jetbrains-lsp ()
  (require 'eglot)
  (should (eq (cdr (assoc "\\.kt\\'" auto-mode-alist))
              'kotlin-ts-mode))
  (should
   (equal (cdr (assq 'kotlin-ts-mode eglot-server-programs))
          '("intellij-server" "--stdio"))))

(ert-deftest my/tree-sitter-parsers-use-neovim-library-names ()
  (should
   (equal treesit-load-name-override-list
          '((c-sharp "c_sharp" "tree_sitter_c_sharp")
            (html "html" "tree_sitter_html")
            (java "java" "tree_sitter_java")
            (javascript "javascript" "tree_sitter_javascript")
            (json "json" "tree_sitter_json")
            (kotlin "kotlin" "tree_sitter_kotlin")
            (python "python" "tree_sitter_python")
            (tsx "tsx" "tree_sitter_tsx")
            (typescript "typescript" "tree_sitter_typescript")
            (yaml "yaml" "tree_sitter_yaml")))))

(ert-deftest my/org-srs-localleader-is-attached-before-org-srs-loads ()
  (should (eq (keymap-lookup my/org-localleader-map "R")
              my/org-srs-map)))

(ert-deftest my/org-align-all-tags-aligns-every-headline ()
  (let (all)
    (cl-letf (((symbol-function 'org-align-tags)
               (lambda (&optional value)
                 (setq all value))))
      (my/org-align-all-tags))
    (should all)))

(ert-deftest my/org-enable-align-tags-on-save-adds-a-buffer-local-hook ()
  (with-temp-buffer
    (setq-local before-save-hook nil)
    (my/org-enable-align-tags-on-save)
    (should (local-variable-p 'before-save-hook))
    (should (memq #'my/org-align-all-tags before-save-hook))))

(ert-deftest my/evil-normal-state-and-save-enters-normal-state-before-saving ()
  (let (calls)
    (cl-letf (((symbol-function 'evil-normal-state)
               (lambda () (push 'normal-state calls)))
              ((symbol-function 'save-buffer)
               (lambda () (push 'save calls))))
      (my/evil-normal-state-and-save))
    (should (equal (nreverse calls) '(normal-state save)))))

(ert-deftest my/evil-open-line-and-stay-normal-commands-dispatch-in-order ()
  (dolist (entry '((my/evil-open-line-above-and-stay-normal
                    . evil-open-above)
                   (my/evil-open-line-below-and-stay-normal
                    . evil-open-below)))
    (let (calls)
      (cl-letf (((symbol-function (cdr entry))
                 (lambda (count)
                   (push (list (cdr entry) count) calls)))
                ((symbol-function 'evil-normal-state)
                 (lambda (&optional _count)
                   (push 'normal-state calls))))
        (funcall (car entry) 2))
      (should (equal (nreverse calls)
                     (list (list (cdr entry) 2) 'normal-state))))))

(ert-deftest my/evil-smart-beginning-of-line-toggles-indentation-and-column-zero ()
  (with-temp-buffer
    (insert "  alpha\n")
    (goto-char 5)
    (my/evil-smart-beginning-of-line)
    (should (= (point) 3))
    (my/evil-smart-beginning-of-line)
    (should (= (point) 1))
    (my/evil-smart-beginning-of-line)
    (should (= (point) 3))))

(ert-deftest my/evil-command-and-recenter-runs-in-order ()
  (let (calls)
    (cl-letf (((symbol-function 'call-interactively)
               (lambda (command &optional _record-flag _keys)
                 (push command calls)))
              ((symbol-function 'recenter)
               (lambda (&optional _redisplay)
                 (push 'recenter calls))))
      (my/evil-command-and-recenter #'evil-scroll-down))
    (should (equal (nreverse calls) '(evil-scroll-down recenter)))))

(ert-deftest my/evil-centered-motion-wrappers-dispatch-to-evil-commands ()
  (dolist (entry '((my/evil-scroll-down-and-center . evil-scroll-down)
                   (my/evil-scroll-up-and-center . evil-scroll-up)
                   (my/evil-search-next-and-center . evil-search-next)
                   (my/evil-search-previous-and-center . evil-search-previous)
                   (my/evil-backward-paragraph-and-center
                    . evil-backward-paragraph)
                   (my/evil-forward-paragraph-and-center
                    . evil-forward-paragraph)))
    (let (command)
      (cl-letf (((symbol-function 'my/evil-command-and-recenter)
                 (lambda (value)
                   (setq command value))))
        (funcall (car entry)))
      (should (eq command (cdr entry))))))

(ert-deftest my/copy-file-name-copies-the-basename ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/project/archive.tar.gz")
    (let (copied)
      (cl-letf (((symbol-function 'kill-new)
                 (lambda (text &optional _replace)
                   (setq copied text))))
        (my/copy-file-name))
      (should (equal copied "archive.tar.gz")))))

(ert-deftest my/copy-file-name-rejects-a-non-file-buffer ()
  (with-temp-buffer
    (should-error (my/copy-file-name) :type 'user-error)))

(ert-deftest my/copy-project-relative-file-path-copies-a-relative-path ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/project/src/main.el")
    (let (copied)
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _) 'project))
                ((symbol-function 'project-root)
                 (lambda (_project) "/tmp/project/"))
                ((symbol-function 'kill-new)
                 (lambda (text &optional _replace)
                   (setq copied text))))
        (my/copy-project-relative-file-path))
      (should (equal copied "src/main.el")))))

(ert-deftest my/copy-project-relative-file-path-copies-an-absolute-path-without-a-project ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/notes/todo.org")
    (let (copied)
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _) nil))
                ((symbol-function 'kill-new)
                 (lambda (text &optional _replace)
                   (setq copied text))))
        (my/copy-project-relative-file-path))
      (should (equal copied "/tmp/notes/todo.org")))))

(ert-deftest my/copy-project-relative-file-path-rejects-a-non-file-buffer ()
  (with-temp-buffer
    (should-error (my/copy-project-relative-file-path) :type 'user-error)))

(ert-deftest my/copy-region-with-context-copies-project-location-and-code ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/project/src/main.py"
          major-mode 'python-mode)
    (insert "ignored\nprint('first')\nprint('second')\nignored\n")
    (let ((begin (progn (goto-char (point-min))
                        (forward-line 1)
                        (point)))
          (end (progn (goto-char (point-min))
                      (forward-line 3)
                      (point)))
          copied)
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _) 'project))
                ((symbol-function 'project-root)
                 (lambda (_project) "/tmp/project/"))
                ((symbol-function 'kill-new)
                 (lambda (text &optional _replace)
                   (setq copied text))))
        (my/copy-region-with-context begin end))
      (should (equal copied
                     (concat "src/main.py:2\n"
                             "```python\n"
                             "print('first')\n"
                             "print('second')\n"
                             "```"))))))

(ert-deftest my/copy-region-with-context-rejects-a-non-file-buffer ()
  (with-temp-buffer
    (insert "text")
    (should-error (my/copy-region-with-context (point-min) (point-max))
                  :type 'user-error)))

(ert-deftest my/magit-status-fullframe-opens-repository-with-fullframe-display ()
  (let (status-directory display-function)
    (cl-letf (((symbol-function 'magit-toplevel)
               (lambda (&optional _directory) "/tmp/project/"))
              ((symbol-function 'magit-status)
               (lambda (directory &optional _cache)
                 (setq status-directory directory
                       display-function magit-display-buffer-function))))
      (my/magit-status-fullframe)
      (should (equal status-directory "/tmp/project/"))
      (should (eq display-function
                  #'magit-display-buffer-fullframe-status-v1)))))

(ert-deftest my/magit-status-fullframe-rejects-non-git-directory ()
  (cl-letf (((symbol-function 'magit-toplevel)
             (lambda (&optional _directory) nil)))
    (should-error (my/magit-status-fullframe) :type 'user-error)))

(ert-deftest my/vdiff-kill-revision-buffer-preserves-working-tree-buffer ()
  (let ((revision-buffer (generate-new-buffer "revision"))
        (working-tree-buffer (generate-new-buffer "working-tree")))
    (unwind-protect
        (progn
          (my--vdiff-kill-revision-buffer revision-buffer working-tree-buffer)
          (should-not (buffer-live-p revision-buffer))
          (should (buffer-live-p working-tree-buffer)))
      (when (buffer-live-p revision-buffer)
        (kill-buffer revision-buffer))
      (when (buffer-live-p working-tree-buffer)
        (kill-buffer working-tree-buffer)))))

(ert-deftest my/magit-review-file-at-point-compares-tracked-file-with-head ()
  (let ((revision-buffer (generate-new-buffer "revision"))
        (working-tree-buffer (generate-new-buffer "working-tree"))
        arguments)
    (unwind-protect
        (cl-letf (((symbol-function 'magit-current-file)
                   (lambda () "README.md"))
                  ((symbol-function 'magit-toplevel)
                   (lambda (&optional _directory) "/tmp/project/"))
                  ((symbol-function 'magit-file-tracked-p)
                   (lambda (_file) t))
                  ((symbol-function 'magit-find-file-noselect)
                   (lambda (_revision _file &rest _)
                     revision-buffer))
                  ((symbol-function 'get-file-buffer)
                   (lambda (_file) working-tree-buffer))
                  ((symbol-function 'vdiff-buffers)
                   (lambda (&rest args) (setq arguments args))))
          (my/magit-review-file-at-point)
          (should (equal arguments
                         (list revision-buffer working-tree-buffer nil
                               #'my--vdiff-kill-revision-buffer t nil))))
      (when (buffer-live-p revision-buffer)
        (kill-buffer revision-buffer))
      (when (buffer-live-p working-tree-buffer)
        (kill-buffer working-tree-buffer)))))

(ert-deftest my/magit-review-file-at-point-opens-untracked-file-to-the-right ()
  (let ((working-tree-buffer (generate-new-buffer "untracked"))
        displayed selected split)
    (unwind-protect
        (cl-letf (((symbol-function 'magit-current-file)
                   (lambda () "notes.txt"))
                  ((symbol-function 'magit-toplevel)
                   (lambda (&optional _directory) "/tmp/project/"))
                  ((symbol-function 'magit-file-tracked-p)
                   (lambda (_file) nil))
                  ((symbol-function 'get-file-buffer)
                   (lambda (_file) working-tree-buffer))
                  ((symbol-function 'window-in-direction)
                   (lambda (direction &rest _)
                     (should (eq direction 'right))
                     'right-window))
                  ((symbol-function 'split-window-right)
                   (lambda (&optional _size)
                     (setq split t)
                     'new-window))
                  ((symbol-function 'set-window-buffer)
                   (lambda (window buffer &optional _keep-margins)
                     (setq displayed (list window buffer))))
                  ((symbol-function 'select-window)
                   (lambda (window &optional _norecord)
                     (setq selected window))))
          (my/magit-review-file-at-point)
          (should (equal displayed (list 'right-window working-tree-buffer)))
          (should-not split)
          (should (eq selected 'right-window)))
      (when (buffer-live-p working-tree-buffer)
        (kill-buffer working-tree-buffer)))))

(ert-deftest my/magit-review-file-at-point-creates-missing-right-window ()
  (let ((working-tree-buffer (generate-new-buffer "untracked"))
        displayed selected)
    (unwind-protect
        (cl-letf (((symbol-function 'magit-current-file)
                   (lambda () "notes.txt"))
                  ((symbol-function 'magit-toplevel)
                   (lambda (&optional _directory) "/tmp/project/"))
                  ((symbol-function 'magit-file-tracked-p)
                   (lambda (_file) nil))
                  ((symbol-function 'get-file-buffer)
                   (lambda (_file) working-tree-buffer))
                  ((symbol-function 'window-in-direction)
                   (lambda (&rest _) nil))
                  ((symbol-function 'split-window-right)
                   (lambda (&optional _size) 'new-window))
                  ((symbol-function 'set-window-buffer)
                   (lambda (window buffer &optional _keep-margins)
                     (setq displayed (list window buffer))))
                  ((symbol-function 'select-window)
                   (lambda (window &optional _norecord)
                     (setq selected window))))
          (my/magit-review-file-at-point)
          (should (equal displayed (list 'new-window working-tree-buffer)))
          (should (eq selected 'new-window)))
      (when (buffer-live-p working-tree-buffer)
        (kill-buffer working-tree-buffer)))))

(ert-deftest my/magit-review-file-at-point-requires-file-at-point ()
  (cl-letf (((symbol-function 'magit-current-file) #'ignore)
            ((symbol-function 'magit-toplevel)
             (lambda (&optional _directory) "/tmp/project/")))
    (should-error (my/magit-review-file-at-point) :type 'user-error)))

(ert-deftest my/search-symbol-at-point-starts-with-the-current-symbol ()
  (with-temp-buffer
    (insert "alpha beta")
    (goto-char (point-min))
    (let (initial)
      (cl-letf (((symbol-function 'consult-line)
                 (lambda (value &optional _start)
                   (setq initial value))))
        (my/search-symbol-at-point))
      (should (equal initial "alpha")))))

(ert-deftest my/search-symbol-at-point-allows-no-current-symbol ()
  (with-temp-buffer
    (let ((initial 'not-called))
      (cl-letf (((symbol-function 'consult-line)
                 (lambda (value &optional _start)
                   (setq initial value))))
        (my/search-symbol-at-point))
      (should-not initial))))

(ert-deftest my/search-open-buffers-searches-all-buffers ()
  (let (query)
    (cl-letf (((symbol-function 'consult-line-multi)
               (lambda (value &optional _initial)
                 (setq query value))))
      (my/search-open-buffers))
    (should query)))

(ert-deftest my/search-project-symbol-at-point-starts-with-the-current-symbol ()
  (with-temp-buffer
    (insert "alpha beta")
    (goto-char (point-min))
    (let (directory initial)
      (cl-letf (((symbol-function 'consult-ripgrep)
                 (lambda (dir value)
                   (setq directory dir
                         initial value))))
        (my/search-project-symbol-at-point))
      (should-not directory)
      (should (equal initial "alpha")))))

(ert-deftest my/markdown-insert-list-item-appends-an-empty-item ()
  (with-temp-buffer
    (gfm-mode)
    (insert "- Existing item")
    (evil-normal-state)
    (search-backward "Existing")
    (my/markdown-insert-list-item)
    (should (equal (buffer-string) "- Existing item\n- "))
    (should (evil-insert-state-p))))

(ert-deftest my/markdown-insert-task-item-appends-an-empty-task ()
  (with-temp-buffer
    (gfm-mode)
    (insert "- [ ] Existing task")
    (evil-normal-state)
    (search-backward "Existing")
    (my/markdown-insert-task-item)
    (should (equal (buffer-string) "- [ ] Existing task\n- [ ] "))
    (should (evil-insert-state-p))))

(ert-deftest my/markdown-insert-task-item-splits-at-insert-point ()
  (with-temp-buffer
    (gfm-mode)
    (insert "- Existing task remainder")
    (search-backward " remainder")
    (evil-insert-state)
    (my/markdown-insert-task-item)
    (should (equal (buffer-string)
                   "- Existing task\n- [ ] remainder"))
    (should (evil-insert-state-p))))

(ert-deftest my/markdown-insert-heading-respect-content-appends-a-sibling ()
  (with-temp-buffer
    (gfm-mode)
    (insert "# Parent\n\nBody\n\n## Child\n\nChild body\n\n# Next\n")
    (goto-char (point-min))
    (evil-normal-state)
    (my/markdown-insert-heading-respect-content)
    (should (equal (buffer-string)
                   (concat "# Parent\n\nBody\n\n## Child\n\nChild body\n\n"
                           "# \n\n# Next\n")))
    (should (evil-insert-state-p))))

(ert-deftest my/markdown-insert-subheading-respect-content-appends-a-child ()
  (with-temp-buffer
    (gfm-mode)
    (insert "## Parent\n\nBody\n\n## Next\n")
    (goto-char (point-min))
    (evil-normal-state)
    (my/markdown-insert-subheading-respect-content)
    (should (equal (buffer-string)
                   "## Parent\n\nBody\n\n### \n\n## Next\n"))
    (should (evil-insert-state-p))))

(ert-deftest my/markdown-insert-subheading-rejects-level-seven ()
  (with-temp-buffer
    (gfm-mode)
    (insert "###### Parent\n")
    (goto-char (point-min))
    (should-error (my/markdown-insert-subheading-respect-content)
                  :type 'user-error)))

(ert-deftest my/markdown-table-insert-row-below-adds-an-empty-row ()
  (with-temp-buffer
    (gfm-mode)
    (insert "| A | B |\n|---|---|\n| x | y |\n")
    (search-backward "x")
    (evil-normal-state)
    (my/markdown-table-insert-row-below)
    (should (equal (buffer-string)
                   "| A | B |\n|---|---|\n| x | y |\n|   |   |\n"))
    (should (evil-insert-state-p))))

(ert-deftest my/markdown-cut-subtree-kills-the-heading-and-its-children ()
  (with-temp-buffer
    (gfm-mode)
    (insert "# Parent\n\nBody\n\n## Child\n\nChild body\n\n# Next\n")
    (goto-char (point-min))
    (my/markdown-cut-subtree)
    (should (equal (buffer-string) "\n\n# Next\n"))))

(ert-deftest my/markdown-cycle-global-cycles-all-headings ()
  (let (argument)
    (cl-letf (((symbol-function 'markdown-cycle)
               (lambda (&optional value)
                 (setq argument value))))
      (my/markdown-cycle-global))
    (should (eq argument t))))

(ert-deftest my/markdown-setext-headings-are-disabled ()
  (should-not (string-match-p markdown-regex-header
                              "src: ./chapters/example.md\n---"))
  (should (string-match-p markdown-regex-header "## Heading")))

(ert-deftest my/org-find-file-in-notes-searches-org-directory ()
  (let ((org-directory "/tmp/notes")
        arguments)
    (cl-letf (((symbol-function 'project-find-file-in)
               (lambda (&rest values)
                 (setq arguments values))))
      (my/org-find-file-in-notes))
    (should (equal (nth 0 arguments) nil))
    (should (equal (nth 1 arguments) '("/tmp/notes/")))
    (should (equal (project-root (nth 2 arguments)) "/tmp/notes/"))
    (should (equal (nth 3 arguments) t))))

(ert-deftest my/org-browse-notes-opens-org-directory ()
  (let ((org-directory "/tmp/notes")
        directory)
    (cl-letf (((symbol-function 'dired)
               (lambda (value &optional _switches)
                 (setq directory value))))
      (my/org-browse-notes))
    (should (equal directory "/tmp/notes"))))

(ert-deftest my/org-search-notes-searches-org-directory ()
  (let ((org-directory "/tmp/notes")
        directory)
    (cl-letf (((symbol-function 'consult-ripgrep)
               (lambda (&optional value _initial)
                 (setq directory value))))
      (my/org-search-notes))
    (should (equal directory "/tmp/notes"))))

(ert-deftest my/org-command-and-enter-insert-state-runs-in-order ()
  (let (calls)
    (cl-letf (((symbol-function 'call-interactively)
               (lambda (command &optional _record-flag _keys)
                 (push command calls)))
              ((symbol-function 'evil-insert-state)
               (lambda (&optional _count)
                 (push 'insert-state calls))))
      (my/org-command-and-enter-insert-state #'org-insert-subheading))
    (should (equal (nreverse calls)
                   '(org-insert-subheading insert-state)))))

(ert-deftest my/org-meta-return-appends-a-list-item-and-starts-editing ()
  (with-temp-buffer
    (org-mode)
    (insert "- [ ] Existing task")
    (evil-normal-state)
    (search-backward "Existing")
    (my/org-meta-return)
    (should (equal (buffer-string)
                   "- [ ] Existing task\n- "))
    (should (evil-insert-state-p))))

(ert-deftest my/org-meta-shift-return-appends-a-todo-item-and-starts-editing ()
  (with-temp-buffer
    (org-mode)
    (insert "- [ ] Existing task")
    (evil-normal-state)
    (search-backward "Existing")
    (my/org-insert-todo-heading)
    (should (equal (buffer-string)
                   "- [ ] Existing task\n- [ ] "))
    (should (evil-insert-state-p))))

(ert-deftest my/org-return-or-open-link-opens-a-link-at-point ()
  (let (opened count)
    (cl-letf (((symbol-function 'org-in-regexp)
               (lambda (regexp &optional nlines visually)
                 (should (eq regexp org-link-any-re))
                 (should-not nlines)
                 (should visually)
                 t))
              ((symbol-function 'org-open-at-point)
               (lambda (&optional _arg)
                 (setq opened t)))
              ((symbol-function 'evil-ret)
               (lambda (value)
                 (setq count value))))
      (my/org-return-or-open-link 3))
    (should opened)
    (should-not count)))

(ert-deftest my/org-return-or-open-link-preserves-evil-ret-count ()
  (let (opened count)
    (cl-letf (((symbol-function 'org-in-regexp)
               (lambda (&rest _arguments) nil))
              ((symbol-function 'org-open-at-point)
               (lambda (&optional _arg)
                 (setq opened t)))
              ((symbol-function 'evil-ret)
               (lambda (value)
                 (setq count value))))
      (my/org-return-or-open-link 3))
    (should-not opened)
    (should (= count 3))))

(ert-deftest my/org-return-follows-links-in-insert-state ()
  (with-temp-buffer
    (org-mode)
    (insert "[[https://example.com][Example]]")
    (search-backward "Example")
    (let (opened)
      (cl-letf (((symbol-function 'org-open-at-point)
                 (lambda (&optional _arg)
                   (interactive)
                   (setq opened t))))
        (org-return))
      (should opened))))

(ert-deftest my/org-open-fold-shows-entry-and-direct-children ()
  (let (calls)
    (cl-letf (((symbol-function 'org-back-to-heading)
               (lambda (&optional invisible-ok)
                 (push `(back-to-heading ,invisible-ok) calls)))
              ((symbol-function 'org-fold-show-entry)
               (lambda (&optional _hide-drawers)
                 (push 'show-entry calls)))
              ((symbol-function 'org-fold-show-children)
               (lambda (&optional _level)
                 (push 'show-children calls))))
      (my/org-open-fold))
    (should (equal (nreverse calls)
                   '((back-to-heading t) show-entry show-children)))))

(ert-deftest my/org-visible-fold-level-detects-the-current-outline-depth ()
  (save-window-excursion
    (with-temp-buffer
      (org-mode)
      (insert "* Parent\n** Child\n*** Grandchild\n")
      (set-window-buffer (selected-window) (current-buffer))
      (goto-char (point-min))
      (outline-hide-sublevels 2)
      (should (= (my--org-visible-fold-level) 2)))))

(ert-deftest my/org-hide-next-fold-level-decreases-the-visible-level ()
  (let (hidden-to)
    (cl-letf (((symbol-function 'my--org-visible-fold-level)
               (lambda () 3))
              ((symbol-function 'outline-hide-sublevels)
               (lambda (level)
                 (setq hidden-to level))))
      (my/org-hide-next-fold-level))
    (should (= hidden-to 2))))

(ert-deftest my/org-hide-next-fold-level-stops-at-level-one ()
  (let (hidden-to)
    (cl-letf (((symbol-function 'my--org-visible-fold-level)
               (lambda () 1))
              ((symbol-function 'outline-hide-sublevels)
               (lambda (level)
                 (setq hidden-to level))))
      (my/org-hide-next-fold-level))
    (should (= hidden-to 1))))

(ert-deftest my/org-show-next-fold-level-increases-the-visible-level ()
  (let (hidden-to)
    (cl-letf (((symbol-function 'my--org-visible-fold-level)
               (lambda () 3))
              ((symbol-function 'outline-hide-sublevels)
               (lambda (level)
                 (setq hidden-to level))))
      (my/org-show-next-fold-level))
    (should (= hidden-to 4))))

(ert-deftest my/disable-line-numbers-turns-off-line-numbers ()
  (with-temp-buffer
    (display-line-numbers-mode 1)
    (my/disable-line-numbers)
    (should-not display-line-numbers-mode)
    (should-not display-line-numbers)))

(ert-deftest my/delete-trailing-whitespace-on-save-deletes-when-enabled ()
  (with-temp-buffer
    (insert "text  \n")
    (my/delete-trailing-whitespace-on-save)
    (should (equal (buffer-string) "text\n"))))

(ert-deftest my/disable-delete-trailing-whitespace-on-save-preserves-whitespace ()
  (with-temp-buffer
    (insert "text  \n")
    (my/disable-delete-trailing-whitespace-on-save)
    (my/delete-trailing-whitespace-on-save)
    (should-not my--delete-trailing-whitespace-on-save-p)
    (should (equal (buffer-string) "text  \n"))))

(ert-deftest my/org-task-capture-targets-the-inbox-file ()
  (require 'org-capture)
  (let* ((template (assoc "t" org-capture-templates))
         (target (nth 3 template)))
    (should (equal target
                   `(file ,(expand-file-name "inbox.org" org-directory))))))

(ert-deftest my/org-task-capture-separates-top-level-headings ()
  (require 'org-capture)
  (let* ((file (make-temp-file "org-capture-spacing-" nil ".org"
                               "* TODO Existing\n"))
         (template (copy-tree (assoc "t" org-capture-templates)))
         (org-capture-templates (list template)))
    (unwind-protect
        (progn
          (setf (nth 3 template) `(file ,file))
          (org-capture-string "" "t")
          (when (org-capture-get :buffer)
            (org-capture-finalize))
          (with-temp-buffer
            (insert-file-contents file)
            (should (string-match-p
                     "\\* TODO Existing\n\n\\* TODO"
                     (buffer-string)))))
      (ignore-errors (org-capture-kill))
      (delete-file file))))

(ert-deftest my/org-capture-starts-in-evil-insert-state ()
  (require 'org-capture)
  (should (memq #'evil-insert-state org-capture-mode-hook))
  (let ((org-capture-mode-hook '(evil-insert-state))
        called)
    (cl-letf (((symbol-function 'evil-insert-state)
               (lambda (&optional _count)
                 (setq called t))))
      (run-hooks 'org-capture-mode-hook))
    (should called)))

(ert-deftest my/org-gfm-export-uses-the-whole-buffer ()
  (let (clipboard-text)
    (cl-letf (((symbol-function 'kill-new)
               (lambda (text &optional _replace)
                 (setq clipboard-text text))))
      (with-temp-buffer
        (org-mode)
        (insert "* Heading\nText with *bold* and a [[https://example.com][link]].\n")
        (my/org-gfm-export-to-clipboard nil nil nil nil)))
    (should (string-match-p "^# Heading" clipboard-text))
    (should (string-match-p "\\*\\*bold\\*\\*" clipboard-text))
    (should (string-match-p
             "\\[link\\](https://example.com)"
             clipboard-text))))

(ert-deftest my/org-gfm-export-uses-the-active-region ()
  (let (clipboard-text)
    (cl-letf (((symbol-function 'kill-new)
               (lambda (text &optional _replace)
                 (setq clipboard-text text))))
      (with-temp-buffer
        (org-mode)
        (transient-mark-mode 1)
        (insert "* First\nSelected text.\n\n* Second\nExcluded text.\n")
        (goto-char (point-min))
        (set-mark (save-excursion
                    (search-forward "* Second")
                    (line-beginning-position)))
        (activate-mark)
        (my/org-gfm-export-to-clipboard nil nil nil nil)))
    (should (string-match-p "Selected text" clipboard-text))
    (should-not (string-match-p "Excluded text" clipboard-text))))

(ert-deftest my/org-gfm-export-rejects-asynchronous-export ()
  (should-error (my/org-gfm-export-to-clipboard t nil nil nil)
                :type 'user-error))

(ert-deftest my/org-rich-text-export-uses-the-active-region ()
  (let (clipboard kill-ring-text)
    (cl-letf (((symbol-function 'kill-new)
               (lambda (text &optional _replace)
                 (setq kill-ring-text text)))
              ((symbol-function 'gui-set-selection)
               (lambda (_type data)
                 (setq clipboard data))))
      (with-temp-buffer
        (org-mode)
        (insert "* First\nSelected *bold* text.\n\n* Second\nExcluded text.\n")
        (goto-char (point-min))
        (set-mark (save-excursion
                    (search-forward "* Second")
                    (line-beginning-position)))
        (activate-mark)
        (my/org-export-to-clipboard-as-rich-text)))
    (let ((html (get-text-property 0 'text/html clipboard)))
      (should (string-match-p "Selected" kill-ring-text))
      (should-not (string-match-p "Excluded" kill-ring-text))
      (should (string-match-p "Selected" html))
      (should (string-match-p "<b>bold</b>" html))
      (should-not (string-match-p "Excluded" html)))))

(ert-deftest my/org-rich-text-export-uses-the-whole-buffer-without-a-region ()
  (let (clipboard kill-ring-text)
    (cl-letf (((symbol-function 'kill-new)
               (lambda (text &optional _replace)
                 (setq kill-ring-text text)))
              ((symbol-function 'gui-set-selection)
               (lambda (_type data)
                 (setq clipboard data))))
      (with-temp-buffer
        (org-mode)
        (insert "* First\nFirst text.\n\n* Second\nSecond text.\n")
        (my/org-export-to-clipboard-as-rich-text)))
    (let ((html (get-text-property 0 'text/html clipboard)))
      (should (string-match-p "First text" kill-ring-text))
      (should (string-match-p "Second text" kill-ring-text))
      (should (string-match-p "First text" html))
      (should (string-match-p "Second text" html)))))

;;; init-test.el ends here
