;;; init-test.el --- Tests for init.el -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'org)

(ert-deftest my/evil-normal-state-and-save-enters-normal-state-before-saving ()
  (let (calls)
    (cl-letf (((symbol-function 'evil-normal-state)
               (lambda () (push 'normal-state calls)))
              ((symbol-function 'save-buffer)
               (lambda () (push 'save calls))))
      (my/evil-normal-state-and-save))
    (should (equal (nreverse calls) '(normal-state save)))))

(ert-deftest my/copy-file-name-copies-the-basename ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/project/archive.tar.gz")
    (let (copied)
      (cl-letf (((symbol-function 'kill-new)
                 (lambda (text &optional _replace)
                   (setq copied text))))
        (my/copy-file-name))
      (should (equal copied "archive.tar.gz")))))

(ert-deftest my/copy-file-name-rejects-a-non-file-buffer ()
  (with-temp-buffer
    (should-error (my/copy-file-name) :type 'user-error)))

(ert-deftest my/copy-project-relative-file-path-copies-a-relative-path ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/project/src/main.el")
    (let (copied)
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _) 'project))
                ((symbol-function 'project-root)
                 (lambda (_project) "/tmp/project/"))
                ((symbol-function 'kill-new)
                 (lambda (text &optional _replace)
                   (setq copied text))))
        (my/copy-project-relative-file-path))
      (should (equal copied "src/main.el")))))

(ert-deftest my/copy-project-relative-file-path-copies-an-absolute-path-without-a-project ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/notes/todo.org")
    (let (copied)
      (cl-letf (((symbol-function 'project-current)
                 (lambda (&rest _) nil))
                ((symbol-function 'kill-new)
                 (lambda (text &optional _replace)
                   (setq copied text))))
        (my/copy-project-relative-file-path))
      (should (equal copied "/tmp/notes/todo.org")))))

(ert-deftest my/copy-project-relative-file-path-rejects-a-non-file-buffer ()
  (with-temp-buffer
    (should-error (my/copy-project-relative-file-path) :type 'user-error)))

(ert-deftest my/search-symbol-at-point-starts-with-the-current-symbol ()
  (with-temp-buffer
    (insert "alpha beta")
    (goto-char (point-min))
    (let (initial)
      (cl-letf (((symbol-function 'consult-line)
                 (lambda (value &optional _start)
                   (setq initial value))))
        (my/search-symbol-at-point))
      (should (equal initial "alpha")))))

(ert-deftest my/search-symbol-at-point-allows-no-current-symbol ()
  (with-temp-buffer
    (let ((initial 'not-called))
      (cl-letf (((symbol-function 'consult-line)
                 (lambda (value &optional _start)
                   (setq initial value))))
        (my/search-symbol-at-point))
      (should-not initial))))

(ert-deftest my/search-open-buffers-searches-all-buffers ()
  (let (query)
    (cl-letf (((symbol-function 'consult-line-multi)
               (lambda (value &optional _initial)
                 (setq query value))))
      (my/search-open-buffers))
    (should query)))

(ert-deftest my/search-project-symbol-at-point-starts-with-the-current-symbol ()
  (with-temp-buffer
    (insert "alpha beta")
    (goto-char (point-min))
    (let (directory initial)
      (cl-letf (((symbol-function 'consult-ripgrep)
                 (lambda (dir value)
                   (setq directory dir
                         initial value))))
        (my/search-project-symbol-at-point))
      (should-not directory)
      (should (equal initial "alpha")))))

(ert-deftest my/org-find-file-in-notes-searches-org-directory ()
  (let ((org-directory "/tmp/notes")
        arguments)
    (cl-letf (((symbol-function 'project-find-file-in)
               (lambda (&rest values)
                 (setq arguments values))))
      (my/org-find-file-in-notes))
    (should (equal arguments
                   '(nil ("/tmp/notes") nil t)))))

(ert-deftest my/org-browse-notes-opens-org-directory ()
  (let ((org-directory "/tmp/notes")
        directory)
    (cl-letf (((symbol-function 'dired)
               (lambda (value &optional _switches)
                 (setq directory value))))
      (my/org-browse-notes))
    (should (equal directory "/tmp/notes"))))

(ert-deftest my/org-search-notes-searches-org-directory ()
  (let ((org-directory "/tmp/notes")
        directory)
    (cl-letf (((symbol-function 'consult-ripgrep)
               (lambda (&optional value _initial)
                 (setq directory value))))
      (my/org-search-notes))
    (should (equal directory "/tmp/notes"))))

(ert-deftest my/org-rich-text-export-uses-the-active-region ()
  (let (clipboard kill-ring-text)
    (cl-letf (((symbol-function 'kill-new)
               (lambda (text &optional _replace)
                 (setq kill-ring-text text)))
              ((symbol-function 'gui-set-selection)
               (lambda (_type data)
                 (setq clipboard data))))
      (with-temp-buffer
        (org-mode)
        (insert "* First\nSelected *bold* text.\n\n* Second\nExcluded text.\n")
        (goto-char (point-min))
        (set-mark (save-excursion
                    (search-forward "* Second")
                    (line-beginning-position)))
        (activate-mark)
        (my/org-export-to-clipboard-as-rich-text)))
    (let ((html (get-text-property 0 'text/html clipboard)))
      (should (string-match-p "Selected" kill-ring-text))
      (should-not (string-match-p "Excluded" kill-ring-text))
      (should (string-match-p "Selected" html))
      (should (string-match-p "<b>bold</b>" html))
      (should-not (string-match-p "Excluded" html)))))

(ert-deftest my/org-rich-text-export-uses-the-whole-buffer-without-a-region ()
  (let (clipboard kill-ring-text)
    (cl-letf (((symbol-function 'kill-new)
               (lambda (text &optional _replace)
                 (setq kill-ring-text text)))
              ((symbol-function 'gui-set-selection)
               (lambda (_type data)
                 (setq clipboard data))))
      (with-temp-buffer
        (org-mode)
        (insert "* First\nFirst text.\n\n* Second\nSecond text.\n")
        (my/org-export-to-clipboard-as-rich-text)))
    (let ((html (get-text-property 0 'text/html clipboard)))
      (should (string-match-p "First text" kill-ring-text))
      (should (string-match-p "Second text" kill-ring-text))
      (should (string-match-p "First text" html))
      (should (string-match-p "Second text" html)))))

;;; init-test.el ends here
