---
- name: emacs packages are installed
  ansible.builtin.package:
    name: emacs
    state: present

- name: emacs config parent directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: emacs config directory exists
  ansible.builtin.file:
    path: /home/{{ user }}/.config/emacs
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: emacs config files and test support are symlinked
  ansible.builtin.file:
    src: "{{ dotfiles_path }}/emacs/{{ item }}"
    dest: /home/{{ user }}/.config/emacs/{{ item }}
    state: link
    follow: false
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - early-init.el
    - init.el
    - scripts
    - tests
