---
- name: default systemd target is registered
  ansible.builtin.command:
    cmd: systemctl get-default
  register: default_target
  changed_when: false

- name: is_graphical_system fact is set
  ansible.builtin.set_fact:
    is_graphical_system: "{{ default_target.stdout == 'graphical.target' }}"

- name: is_graphical_system fact is printed
  ansible.builtin.debug:
    var: is_graphical_system

- name: downloader tools are installed
  ansible.builtin.package:
    name:
      - curl
      - wget
    state: present

- name: compression tools are installed
  ansible.builtin.package:
    name:
      - xz
      - zip
      - unzip
      - tar
      - p7zip
    state: present

- name: community.general prerequisites are installed
  ansible.builtin.package:
    name:
      - python3-dnf
      - dnf-plugins-core
    state: present

- name: usbutils are installed (lsusb)
  ansible.builtin.package:
    name: usbutils
    state: present

- name: kitty terminfo is installed
  ansible.builtin.package:
    name: kitty-terminfo
    state: present

- name: intel cpu microcode is installed
  ansible.builtin.package:
    name: microcode_ctl
    state: present
  notify: current kernel initramfs is rebuilt
  when:
    - ansible_facts['architecture'] == 'x86_64'
    - ansible_facts['processor'] | select('search', 'GenuineIntel') | length > 0

