---
- name: nodesource repository is configured
  block:
    - name: nodesource repository key file is installed
      ansible.builtin.copy:
        src: nodesource.asc
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-nodesource
        owner: root
        group: root
        mode: 0644

    - name: nodesource repository key is installed
      ansible.builtin.rpm_key:
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-nodesource
        fingerprint: 242b813831af09562b6c46f76b88da4e3af28a14
        state: present

    - name: nodesource-node.js repository is enabled
      ansible.builtin.yum_repository:
        name: nodesource-nodejs
        description: Node.js Packages for Linux RPM based distros
        baseurl: https://rpm.nodesource.com/pub_{{ node_version }}/nodistro/nodejs/x86_64
        enabled: true
        gpgcheck: true
        priority: 10
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-nodesource
        skip_if_unavailable: true

- name: fedora nodejs split packages are absent
  ansible.builtin.package:
    name:
      - nodejs-libs
      - nodejs-full-i18n
      - nodejs-npm
      - nodejs-docs
    state: absent

- name: nodejs is installed
  ansible.builtin.package:
    name: nodejs
    state: present

- name: pnmp is installed
  community.general.npm:
    name: pnpm
    global: true
    state: present
