---
- name: network share group exists with the correct gid
  ansible.builtin.group:
    name: "{{ network_share_group }}"
    gid: "{{ network_share_gid }}"
    state: present

- name: user is in the network share group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: "{{ network_share_group }}"
    append: true

- name: nfs tasks
  ansible.builtin.import_tasks: nfs.yml

# - name: samba tasks
#   ansible.builtin.import_tasks: samba.yml
