---
- name: gradia is installed (screenshot annotation tool)
  community.general.flatpak:
    name: be.alexandervanhee.gradia
    state: present

- name: satty binary is removed
  ansible.builtin.file:
    path: /home/{{ user }}/bin/satty
    state: absent
