---
- name: gemini cli is absent
  community.general.npm:
    name: "@google/gemini-cli"
    global: true
    state: absent

- name: antigravity cli is installed
  ansible.builtin.shell:
    cmd: curl -fsSL https://antigravity.google/cli/install.sh | bash  # noqa: command-instead-of-module
    creates: /home/{{ user }}/.local/bin/agy
  become: true
  become_user: "{{ user }}"

- name: codex is installed
  community.general.npm:
    name: "@openai/codex"
    global: true
    state: present

- name: opencode is installed
  community.general.npm:
    name: "opencode-ai"
    global: true
    state: present

- name: claude code is installed
  ansible.builtin.shell:
    cmd: curl -fsSL https://claude.ai/install.sh | bash  # noqa: command-instead-of-module
    creates: /home/{{ user }}/.local/bin/claude
  become: true
  become_user: "{{ user }}"

